/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Responde 200 enquanto o processo estiver de pé. Não toca no banco.
         */
        get: operations["healthLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Verifica as dependências externas — hoje, a conexão com o banco.
         */
        get: operations["healthReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar uma conta */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abrir sessão
         * @description Devolve o access token no corpo — o cliente o mantém **em memória**.
         *     O refresh token vai em cookie `httpOnly; Secure; SameSite=Lax` e nunca
         *     aparece no corpo da resposta.
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotacionar o access token
         * @description Lê o refresh token do cookie, revoga-o e emite um par novo.
         *     Reuso de um refresh já consumido invalida toda a família de tokens.
         */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerrar sessão
         * @description Revoga o refresh token e limpa o cookie.
         */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil do portador do token */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar usuários */
        get: operations["usersList"];
        put?: never;
        /** Criar usuário */
        post: operations["usersCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /** Obter usuário */
        get: operations["usersGet"];
        put?: never;
        post?: never;
        /** Remover usuário */
        delete: operations["usersDelete"];
        options?: never;
        head?: never;
        /**
         * Atualizar usuário
         * @description Atualização parcial. Campos ausentes permanecem inalterados.
         */
        patch: operations["usersUpdate"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: email
         * @example ana@exemplo.com
         */
        Email: string;
        /** @description Envelope de erro conforme a RFC 9457. */
        Problem: {
            /**
             * Format: uri
             * @description URI que identifica o tipo do problema.
             */
            type: string;
            /** @description Resumo curto e estável do tipo do problema. */
            title: string;
            /** @description O mesmo código HTTP da resposta. */
            status: number;
            /** @description Explicação legível, específica desta ocorrência. */
            detail?: string;
            /**
             * Format: uri
             * @description URI da ocorrência específica.
             */
            instance?: string;
        };
        ValidationProblem: components["schemas"]["Problem"] & {
            /** @description Um item por campo rejeitado. */
            errors: {
                field: string;
                message: string;
            }[];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "unhealthy";
            alive: boolean;
            ready: boolean;
        };
        User: {
            /** Format: uuid */
            id: string;
            email: components["schemas"]["Email"];
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RegisterRequest: {
            email: components["schemas"]["Email"];
            name: string;
            /**
             * Format: password
             * @description Mínimo de 12 caracteres. Hash com argon2id.
             */
            password: string;
        };
        LoginRequest: {
            email: components["schemas"]["Email"];
            /** Format: password */
            password: string;
        };
        TokenResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @description Vida do access token, em segundos. */
            expires_in: number;
        };
        UserCreate: {
            email: components["schemas"]["Email"];
            name: string;
            /** Format: password */
            password: string;
        };
        UserUpdate: {
            email?: components["schemas"]["Email"];
            name?: string;
        };
        PageMeta: {
            page: number;
            per_page: number;
            total: number;
            total_pages: number;
        };
        UserPage: {
            items: components["schemas"]["User"][];
            meta: components["schemas"]["PageMeta"];
        };
    };
    responses: {
        /** @description Credenciais ausentes, inválidas ou expiradas. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://lopestech.dev/errors/unauthorized",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "detail": "Credenciais inválidas."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description O corpo não pôde ser lido. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://lopestech.dev/errors/bad-request",
                 *       "title": "Bad Request",
                 *       "status": 400,
                 *       "detail": "A requisição não pôde ser lida."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description O recurso não existe. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://lopestech.dev/errors/not-found",
                 *       "title": "Not Found",
                 *       "status": 404,
                 *       "detail": "Usuário não encontrado."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Violação de uma regra de unicidade. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://lopestech.dev/errors/conflict",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "detail": "Já existe uma conta com este e-mail."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description O corpo ou os parâmetros não passaram na validação. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://lopestech.dev/errors/validation",
                 *       "title": "Validation failed",
                 *       "status": 422,
                 *       "detail": "O corpo da requisição contém campos inválidos.",
                 *       "errors": [
                 *         {
                 *           "field": "email",
                 *           "message": "formato inválido"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
    };
    parameters: {
        Page: number;
        PerPage: number;
        UserId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A aplicação está viva. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "alive": true,
                     *       "ready": true
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    healthReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A aplicação está pronta para receber tráfego. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "alive": true,
                     *       "ready": true
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Alguma dependência está indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "unhealthy",
                     *       "alive": true,
                     *       "ready": false
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Conta criada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Sessão aberta. */
            200: {
                headers: {
                    /** @description refresh_token=<opaco>; HttpOnly; Secure; SameSite=Lax; Path=/api/v1/auth */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token renovado. */
            200: {
                headers: {
                    /** @description Novo refresh token, rotacionado. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada. */
            204: {
                headers: {
                    /** @description Cookie expirado. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O usuário autenticado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    usersList: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
                /** @description Busca parcial e insensível a maiúsculas por e-mail ou nome. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de usuários. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    usersCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Usuário criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    usersGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O usuário. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    usersDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário removido. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    usersUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Usuário atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
}
